#!/bin/sh

echo "Blockmesh starts"
blockMesh >> log 2>&1

# Sequential running

#echo "Setrandomfield starts"
#setRandomField >> log 2>&1

#echo "Simpledarcyfoam starts"
#simpleDarcyFoam -noFunctionObjects >> log 2>&1

#find ./ -name 'U' | while read U ; do cp "$U" ./0 ; done

echo "Decomposition of the domain starts"
decomposePar >> log 2>&1

echo "Setrandomfield starts"
mpirun --oversubscribe -np 12 setRandomField -parallel >> log 2>&1

echo "Simpledarcyfoam starts"
mpirun --oversubscribe -np 12 simpleDarcyFoam -noFunctionObjects -parallel  >> log 2>&1 # Parallel running

for i in processor*; do
    cd ./$i
    find ./ -name 'U' | while read U ; do cp "$U" ./0 ; done 
    cd ..
done

echo "ScalarTransportFoam starts"
mpirun --oversubscribe -np 12 scalarTransportFoam -parallel  >> log 2>&1

echo "FieldMetrics strats"
mpirun --oversubscribe -np 12 postProcess -time 0 -dict system/fieldMetricsDict -parallel >> log 2>&1

echo "Finish"
