#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
@author: Eugenio Pescimoro
@email: eugenio.pescimoro@gmail.com
@Description: Plot average velocities stored in output log file from OpenFOAM simpleDarcyFoam solver against simulation number
"""

# Import section ############################################################## 
from operator import itemgetter
import matplotlib.pyplot as plt
import os
import re

# Initialization ##############################################################
cl = []
lcorr = []
mvel = []
sim = 28

# Loop through simulation folders and parse files (setRandomFieldDict, log and corrLengths.mat)
for i in range(1, sim+1): # Range of simulations which should be plotted
    os.chdir('/data/GMRTFoam/tutorials/simpleDarcyFoam/RESULTS/Python/veLcorrTransport/TS%d/system' % i)
    with open("setRandomFieldDict") as RF:
        for line in RF:
            if "Lcorr" in line:
                lcorr.append([float(i) for i in re.split(' |\(|\)', line)[slice(12, 15)]])
                break
    os.chdir('..')
    with open("log") as log:
        parse = False
        for line in log: # It greps all the relevant data from the log file
            if "simpleDarcyFoam" in line:
                parse = True
            if "postProcess" in line:
                parse = False        
            if parse == True and "Mean velocity  =" in line:
                mvel.append([float(i) for i in re.split(' |\(|\)', line)[slice(5, 8)]])
                break
    os.chdir('..')
with open("corrLengths.mat") as CL:
    for line in CL:
        if not any(value in line for value in "#"):
                cl.append([float(i) for i in re.split(' ', line)[slice(1, 4)]])
    cl = [sublist for sublist in cl if any(sublist)] # It deletes the empty sublists generated by Octave
x = list(map(itemgetter(0), cl))
y = list(map(itemgetter(1), cl))
z = list(map(itemgetter(2), cl))

# Plot average Vx, Vy and Vz against the simulation number ####################
plt.rc('font', size=30)
fig1 = plt.figure(figsize=(14, 14))
ax = fig1.add_subplot(1, 1, 1)
ax.plot(list([i for i in range(10)]), list(map(itemgetter(0), mvel[:10])), 'ro')
ax.plot(list([i for i in range(11, 20)]), list(map(itemgetter(0), mvel[11:20])), 'bo')
ax.plot(list([i for i in range(21, sim)]), list(map(itemgetter(0), mvel[21:sim])), 'go')
ax.set_xlabel('Simulation number [-]')
ax.set_ylabel('Average Vx [m/s]')
ax.ticklabel_format(axis = 'y', style = 'sci', scilimits = (0,0))
ax.set_ylim([0.5e-5, 1.1e-5])
plt.tight_layout()
fig1.savefig("/home/pmxep5/OneDrive/Nottingham/Results/Images/veLcorrTransport/aveVxNonPeriodic.pdf")
#plt.show()
fig2 = plt.figure(figsize=(14, 14))
ax = fig2.add_subplot(1, 1, 1)
ax.plot(list([i for i in range(10)]), list(map(itemgetter(1), mvel[:10])), 'ro')
ax.plot(list([i for i in range(11, 20)]), list(map(itemgetter(1), mvel[11:20])), 'bo')
ax.plot(list([i for i in range(21, sim)]), list(map(itemgetter(1), mvel[21:sim])), 'go')
ax.set_xlabel('Simulation number [-]')
ax.set_ylabel('Average Vy [m/s]')
ax.set_ylim([-5.5e-7, 3.5e-7])
plt.tight_layout()
fig2.savefig("/home/pmxep5/OneDrive/Nottingham/Results/Images/veLcorrTransport/aveVyNonPeriodic.pdf")
#plt.show()
fig3 = plt.figure(figsize=(14, 14))
ax = fig3.add_subplot(1, 1, 1)
ax.plot(list([i for i in range(10)]), list(map(itemgetter(2), mvel[:10])), 'ro')
ax.plot(list([i for i in range(11, 20)]), list(map(itemgetter(2), mvel[11:20])), 'bo')
ax.plot(list([i for i in range(21, sim)]), list(map(itemgetter(2), mvel[21:sim])), 'go')
ax.set_xlabel('Simulation number [-]')
ax.set_ylabel('Average Vz [m/s]')
ax.set_ylim([-5.5e-7, 3.5e-7])
plt.tight_layout()
fig3.savefig("/home/pmxep5/OneDrive/Nottingham/Results/Images/veLcorrTransport/aveVzNonPeriodic.pdf")
#plt.show()
